Author:
[Vishnupriya Venkateswaran]
[04/22/19]

In [1]:
import numpy as np
import pandas as pd
import nltk
from nltk.tokenize import sent_tokenize
#nltk.download('punkt') # one time execution
import re

from nltk.tokenize import word_tokenize
from nltk.translate.bleu_score import sentence_bleu

In [2]:
# Upload the CSV file
#from google.colab import files
#uploaded = files.upload()

In [3]:
# Read the CSV file
import io
df = pd.read_csv('Speeches.csv',encoding = "ISO-8859-1")

In [4]:
df.head()

speech_id                                        speech_text
0          1  For myself and for our Nation, I want to thank...
1          2  Senator Hatfield, Mr. Chief Justice, Mr. Presi...
2          3  Senator Mathias, Chief Justice Burger, Vice Pr...
3          4  Mr. Chief Justice, Mr. President, Vice Preside...
4          5  My fellow citizens, today we celebrate the mys...

In [5]:
# split the the text in the speech into sentences
sentences = []
for s in df['speech_text']:
      sentences.append(sent_tokenize(s))  

In [6]:
# flatten the list
sentences = [y for x in sentences for y in x]
print(sentences)

reference = []
for s in sentences:
    reference.append(word_tokenize(s))
    
print(reference)

['For myself and for our Nation, I want to thank my predecessor for all he has done to heal our land.', 'In this outward and physical ceremony, we attest once again to the inner and spiritual strength of our Nation.', 'As my high school teacher, Miss Julia Coleman, used to say, "We must adjust to changing times and still hold to unchanging principles."', 'Here before me is the Bible used in the inauguration of our first President, in 1789, and I have just taken the oath of office on the Bible my mother gave me just a few years ago, opened to a timeless admonition from the ancient prophet Micah: "He hath showed thee, O man, what is good; and what doth the Lord require of thee, but to do justly, and to love mercy, and to walk humbly with thy God."', 'This inauguration ceremony marks a new beginning, a new dedication within our Government, and a new spirit among us all.', 'A President may sense and proclaim that new spirit, but only a people can provide it.', "Two centuries ago, our Natio

In [8]:
candidate = "We must think anew and move with a new boldness, so every American who seeks work can find work, so the least among us shall have an equal chance to achieve the greatest things to be heroes who heal our sick, feed the hungry, protect peace among nations, and leave this world a better place."

In [9]:
candidate_sentences = sent_tokenize(candidate)
print(candidate_sentences)

['We must think anew and move with a new boldness, so every American who seeks work can find work, so the least among us shall have an equal chance to achieve the greatest things to be heroes who heal our sick, feed the hungry, protect peace among nations, and leave this world a better place.']


In [10]:
candidate = []
for s in candidate_sentences:
    candidate.append(word_tokenize(s))
    
print(candidate)

[['We', 'must', 'think', 'anew', 'and', 'move', 'with', 'a', 'new', 'boldness', ',', 'so', 'every', 'American', 'who', 'seeks', 'work', 'can', 'find', 'work', ',', 'so', 'the', 'least', 'among', 'us', 'shall', 'have', 'an', 'equal', 'chance', 'to', 'achieve', 'the', 'greatest', 'things', 'to', 'be', 'heroes', 'who', 'heal', 'our', 'sick', ',', 'feed', 'the', 'hungry', ',', 'protect', 'peace', 'among', 'nations', ',', 'and', 'leave', 'this', 'world', 'a', 'better', 'place', '.']]


In [13]:
score = sentence_bleu(reference, candidate[0])
print(score)

0.9525961551041779


In [15]:
reference1 = [['a', 'new', 'breeze', 'is', 'blowing','and','the','old','bipartisanship','must','be','made','new','again']]
candidate1 = ['a','new','breeze','breeze','blowing','blowing','the','the','bipartisanship','must','must','made','made','be']
score1 = sentence_bleu(reference1, candidate1)
print(score1)

4.072526232117304e-78


/Applications/anaconda3/lib/python3.6/site-packages/nltk/translate/bleu_score.py:523: UserWarning: 
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)


In [7]:
# remove punctuations, numbers and special characters
clean_sentences = pd.Series(sentences).str.replace("[^a-zA-Z]", " ")

# make alphabets lowercase
clean_sentences = [s.lower() for s in clean_sentences]

print(clean_sentences)

['for myself and for our nation  i want to thank my predecessor for all he has done to heal our land ', 'in this outward and physical ceremony  we attest once again to the inner and spiritual strength of our nation ', 'as my high school teacher  miss julia coleman  used to say   we must adjust to changing times and still hold to unchanging principles  ', 'here before me is the bible used in the inauguration of our first president  in       and i have just taken the oath of office on the bible my mother gave me just a few years ago  opened to a timeless admonition from the ancient prophet micah   he hath showed thee  o man  what is good  and what doth the lord require of thee  but to do justly  and to love mercy  and to walk humbly with thy god  ', 'this inauguration ceremony marks a new beginning  a new dedication within our government  and a new spirit among us all ', 'a president may sense and proclaim that new spirit  but only a people can provide it ', 'two centuries ago  our natio

In [8]:
#nltk.download('stopwords')# one time execution

In [9]:
from nltk.corpus import stopwords
stop_words = stopwords.words('english')

print(stop_words)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [10]:
# function to remove stopwords
def remove_stopwords(sen):
      sen_new = " ".join([i for i in sen if i not in stop_words])
          return sen_new

In [11]:
# remove stopwords from the sentences
clean_sentences = [remove_stopwords(r.split()) for r in clean_sentences]

print(clean_sentences)

['nation want thank predecessor done heal land', 'outward physical ceremony attest inner spiritual strength nation', 'high school teacher miss julia coleman used say must adjust changing times still hold unchanging principles', 'bible used inauguration first president taken oath office bible mother gave years ago opened timeless admonition ancient prophet micah hath showed thee man good doth lord require thee justly love mercy walk humbly thy god', 'inauguration ceremony marks new beginning new dedication within government new spirit among us', 'president may sense proclaim new spirit people provide', 'two centuries ago nation birth milestone long quest freedom', 'bold brilliant dream excited founders nation still awaits consummation', 'new dream set forth today rather urge fresh faith old dream', 'first society openly define terms spirituality human liberty', 'unique self definition given us exceptional appeal also imposes us special obligation take moral duties assumed seem invariabl

In [12]:
!wget http://nlp.stanford.edu/data/glove.6B.zip 
!unzip glove*.zip

/bin/sh: wget: command not found
Archive:  glove.6B.zip
  inflating: glove.6B.50d.txt        
  inflating: glove.6B.100d.txt       
  inflating: glove.6B.200d.txt       
  inflating: glove.6B.300d.txt       


In [13]:
# Extract word vectors
word_embeddings = {}
f = open('glove.6B.100d.txt', encoding='utf-8')
for line in f:
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    word_embeddings[word] = coefs
f.close()

In [14]:
sentence_vectors = []
for i in clean_sentences:
    if len(i) != 0:
        v = sum([word_embeddings.get(w, np.zeros((100,))) for w in i.split()])/(len(i.split())+0.001)
    else:
        v = np.zeros((100,))
    sentence_vectors.append(v)

In [15]:
len(sentence_vectors)

1158

The next step is to find similarities among the sentences. We will use cosine similarity to find similarity between a pair of sentences. Let's create an empty similarity matrix for this task and populate it with cosine similarities of the sentences.

In [16]:
# similarity matrix
sim_mat = np.zeros([len(sentences), len(sentences)])

print(sim_mat)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [17]:
from sklearn.metrics.pairwise import cosine_similarity

In [18]:
for i in range(len(sentences)):
      for j in range(len(sentences)):
        if i != j:
              sim_mat[i][j] = cosine_similarity(sentence_vectors[i].reshape(1,100), sentence_vectors[j].reshape(1,100))[0,0]

In [19]:
import networkx as nx

nx_graph = nx.from_numpy_array(sim_mat)
scores = nx.pagerank(nx_graph)
print(scores)

{0: 0.0009224538922685656, 1: 0.0008124269784651946, 2: 0.000925621611602791, 3: 0.0008621797048966828, 4: 0.0009101718390401705, 5: 0.0009427100143014605, 6: 0.000904761826310563, 7: 0.000833766496910615, 8: 0.0009425255602991984, 9: 0.0008774630770939451, 10: 0.0009296962013576349, 11: 0.0009109422695182589, 12: 0.0009286709587002964, 13: 0.0007924788543741159, 14: 0.0009134127799136046, 15: 0.0007744302480457182, 16: 0.0009626971877097754, 17: 0.0009246917395104316, 18: 0.0008522179317953337, 19: 0.0009407819373805453, 20: 0.0008592509324267168, 21: 0.0008210013381531945, 22: 0.0008283710712621062, 23: 0.0007500224880701208, 24: 0.0008654874395467035, 25: 0.0008720551928998538, 26: 0.0009089243836399114, 27: 0.0009029662397303568, 28: 0.0009377215630169767, 29: 0.0008807611161712337, 30: 0.0009304924186500098, 31: 0.000899096566963904, 32: 0.0009232669291380374, 33: 0.0009218007440932044, 34: 0.0009321793780590703, 35: 0.0008765861515316313, 36: 0.0009163877332654444, 37: 0.00082985

In [20]:
ranked_sentences = sorted(((scores[i],s) for i,s in enumerate(sentences)), reverse=True)
print(ranked_sentences)

[(0.0009776589389517438, 'We must think anew and move with a new boldness, so every American who seeks work can find work, so the least among us shall have an equal chance to achieve the greatest thingsÑto be heroes who heal our sick, feed the hungry, protect peace among nations, and leave this world a better place.'), (0.000973811477333424, 'And I join in the hope that when my time as your President has ended, people might say this about our Nation:\nthat we had remembered the words of Micah and renewed oursearch for humility, mercy, and justice;\nthat we had torn down the barriers that separated those of different race and region and religion, and where there had been mistrust, built unity, with a respect for diversity;\nthat we had found productive work for those able to perform it;\nthat we had strengthened the American family, which is the basis of our society;\nthat we had ensured respect for the law and equal treatment under the law, for the weak and the powerful, for the rich a

In [21]:
# Specify number of sentences to form the summary
sn = 1

# Generate summary
for i in range(sn):
      print(ranked_sentences[i][1])

We must think anew and move with a new boldness, so every American who seeks work can find work, so the least among us shall have an equal chance to achieve the greatest thingsÑto be heroes who heal our sick, feed the hungry, protect peace among nations, and leave this world a better place.
